"""
Agent 2: Interviewer Agent (OpenRouter API)
-----------------------------------------------------
Adaptive, role-specific interviewer agent.
Asks up to 5 questions, saves answers, asks clarifying questions only if needed.
"""

import os
import json
import requests
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
if not OPENAI_API_KEY:
    raise ValueError("OpenAI API key missing in .env")

MODEL = "gpt-4o-mini"
API_URL = "https://openrouter.ai/api/v1/chat/completions"


class InterviewerAgent:
    def __init__(self, role: str, candidate_info: str):
        self.role = role
        self.candidate_info = candidate_info
        self.conversation_history = []  # stores question/answer pairs
        self.max_questions = 5

    def ask_question(self) -> str:
        """
        Call OpenRouter API to get the next question based on conversation history
        """
        system_prompt = f"""
You are a structured interviewer for the role: {self.role}.
Rules:
- Ask a maximum of {self.max_questions} role-specific questions.
- Follow the rubric strictly (skills, experience, problem-solving).
- Do NOT engage in free-form chat.
- Ask follow-up questions only if previous answer is ambiguous.
- Return output ONLY as JSON with:
  - questions_asked: list of previous questions and answers
  - next_question: next question to ask (or null if max questions reached)
  - interview_summary: short assessment at the end
"""

        user_prompt = f"""
Candidate information:
{self.candidate_info}

Conversation history:
{json.dumps(self.conversation_history, indent=2)}

Task:
Ask the next interview question based on the conversation history.
Return JSON only.
"""

        payload = {
            "model": MODEL,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": 0.2,
        }

        headers = {
            "Authorization": f"Bearer {OPENAI_API_KEY}",
            "Content-Type": "application/json",
        }

        try:
            response = requests.post(API_URL, headers=headers, json=payload, timeout=30)
            response.raise_for_status()
            data = response.json()
            raw_output = data["choices"][0]["message"]["content"]
            return json.loads(raw_output)
        except Exception as e:
            return {"error": f"Failed to get question: {str(e)}", "raw_output": raw_output if 'raw_output' in locals() else ""}

    def run_interview(self):
        """
        Run the interview loop for up to max_questions
        """
        question_count = 0

        while question_count < self.max_questions:
            result = self.ask_question()

            if "error" in result:
                print(result["error"])
                break

            next_question = result.get("next_question")
            questions_asked = result.get("questions_asked", [])
            interview_summary = result.get("interview_summary", "")

            if not next_question:
                print("\nNo more questions generated by the agent.")
                break

            # Ask user the next question
            print(f"\nQuestion {question_count + 1}: {next_question}")
            answer = input("Candidate answer: ").strip()

            # Append to conversation history
            self.conversation_history = questions_asked
            self.conversation_history.append({
                "question": next_question,
                "candidate_answer": answer
            })

            question_count += 1

        # Final interview summary
        print("\nInterview Summary:")
        print(interview_summary)
        print("\nFull Q&A:")
        print(json.dumps(self.conversation_history, indent=2))


def main():
    role = "Frontend Developer"
    candidate_info = """
Frontend Developer Intern with experience in React, JavaScript,
API integration, and UI development. Worked on production MVPs
using React and Tailwind CSS.
"""

    agent = InterviewerAgent(role, candidate_info)
    agent.run_interview()


if __name__ == "__main__":
    main()